import type { Session, ItineraryVersion, ChatMessage } from './schemas'

const SESSION_ID = '00000000-0000-4000-a000-000000000001'

// Reusable UUIDs for versions
const V0_ID = '00000000-0000-4000-a000-000000000010'
const V1_ID = '00000000-0000-4000-a000-000000000011'
const V2_ID = '00000000-0000-4000-a000-000000000012'
const V3_ID = '00000000-0000-4000-a000-000000000013'
const V4_ID = '00000000-0000-4000-a000-000000000014'

export const mockSession: Session = {
  id: SESSION_ID,
  destination: 'Paris',
  durationHours: 48,
  agents: ['flaneur', 'completionist'],
  status: 'complete',
  createdAt: '2026-02-28T09:00:00Z',
}

export const mockVersions: ItineraryVersion[] = [
  // --- Version 0: Flaneur proposal ---
  {
    id: V0_ID,
    sessionId: SESSION_ID,
    versionNumber: 0,
    agentId: 'flaneur',
    commentary: 'I\'ve designed a Paris itinerary that lets you *feel* the city rather than just photograph it. Mornings start slow with local cafes, afternoons are for wandering, and evenings settle into wherever the day takes you.',
    days: [
      {
        dayNumber: 1,
        theme: 'Left Bank Drift',
        activities: [
          {
            id: '10000000-0000-4000-a000-000000000001',
            timeBlock: '09:00–10:30',
            title: 'Café de Flore Morning',
            description: 'Start with a café crème at this Saint-Germain institution. Watch the neighborhood wake up from a terrace seat.',
            location: '172 Boulevard Saint-Germain, 75006',
            durationMinutes: 90,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'A proper Parisian morning starts slowly. Café de Flore sets the rhythm — you\'re not a tourist rushing to a queue, you\'re someone who lives here for a day.',
          },
          {
            id: '10000000-0000-4000-a000-000000000002',
            timeBlock: '10:30–12:30',
            title: 'Rue Mouffetard Market Stroll',
            description: 'Wander one of Paris\'s oldest market streets. Sample cheese, grab fruit, and soak in the atmosphere.',
            location: 'Rue Mouffetard, 75005',
            durationMinutes: 120,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Markets are where a city reveals its true character. Mouffetard is walkable from Saint-Germain and feels genuinely local.',
          },
          {
            id: '10000000-0000-4000-a000-000000000003',
            timeBlock: '12:30–14:00',
            title: 'Lunch at Le Comptoir du Panthéon',
            description: 'Casual bistro lunch with a view of the Panthéon. Try the croque monsieur or the plat du jour.',
            location: '5 Rue Soufflot, 75005',
            durationMinutes: 90,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'You\'re already in the 5th — no need to rush elsewhere. This spot offers good food without the tourist markup.',
          },
          {
            id: '10000000-0000-4000-a000-000000000004',
            timeBlock: '14:00–17:00',
            title: 'Luxembourg Gardens & Latin Quarter Drift',
            description: 'No agenda. Wander the gardens, sit by the fountain, browse bookshops on Rue de la Huchette. Follow your curiosity.',
            location: 'Jardin du Luxembourg, 75006',
            durationMinutes: 180,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'The best Paris moments are unscripted. Three hours of open time lets serendipity happen — a jazz busker, a hidden courtyard, a perfect bench.',
          },
          {
            id: '10000000-0000-4000-a000-000000000005',
            timeBlock: '19:00–21:30',
            title: 'Dinner in Le Marais',
            description: 'Walk to Le Marais for dinner. Try Chez Janou for their legendary chocolate mousse, or explore the Jewish Quarter\'s falafel row.',
            location: 'Le Marais, 75004',
            durationMinutes: 150,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'Le Marais at dusk is magical. The neighborhood rewards those who arrive without a rigid plan — just pick the restaurant with the best energy.',
          },
        ],
      },
      {
        dayNumber: 2,
        theme: 'Montmartre & Canal Saint-Martin',
        activities: [
          {
            id: '10000000-0000-4000-a000-000000000006',
            timeBlock: '09:00–10:00',
            title: 'Boulangerie Breakfast in Montmartre',
            description: 'Fresh croissants and pain au chocolat from a neighborhood boulangerie. Eat on a bench overlooking the city.',
            location: 'Rue Lepic, Montmartre, 75018',
            durationMinutes: 60,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'Skip the sit-down breakfast — grab pastries and find a spot with a view. Montmartre mornings belong to the locals before the crowds arrive.',
          },
          {
            id: '10000000-0000-4000-a000-000000000007',
            timeBlock: '10:00–12:30',
            title: 'Montmartre Village Wander',
            description: 'Explore the cobblestone streets behind Sacré-Cœur. Visit the vineyard, peek into artist studios, find the quieter squares.',
            location: 'Montmartre, 75018',
            durationMinutes: 150,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Tourist Montmartre is the front of Sacré-Cœur. Real Montmartre is behind it — the tiny streets, the hidden staircases, the village feel.',
          },
          {
            id: '10000000-0000-4000-a000-000000000008',
            timeBlock: '13:00–14:30',
            title: 'Canal Saint-Martin Picnic',
            description: 'Pick up supplies from a fromagerie and settle along the canal. Watch the locks operate and boats pass through.',
            location: 'Canal Saint-Martin, 75010',
            durationMinutes: 90,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'A canal-side picnic is peak Parisian living. It\'s free, it\'s social, and it gives you front-row seats to neighborhood life.',
          },
          {
            id: '10000000-0000-4000-a000-000000000009',
            timeBlock: '15:00–18:00',
            title: 'Canal Walks & Vintage Shopping',
            description: 'Follow the canal north, browse vintage shops and independent boutiques along Rue Beaurepaire and Rue de Marseille.',
            location: 'Canal Saint-Martin area, 75010',
            durationMinutes: 180,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'The 10th arrondissement is where young Parisians actually hang out. The vintage shops are genuinely curated, not tourist traps.',
          },
          {
            id: '10000000-0000-4000-a000-000000000010',
            timeBlock: '20:00–22:00',
            title: 'Natural Wine Bar Evening',
            description: 'End at a natural wine bar like Le Verre Volé. Small plates, interesting bottles, conversation with locals.',
            location: '67 Rue de Lancry, 75010',
            durationMinutes: 120,
            category: 'nightlife',
            agentOrigin: 'flaneur',
            agentLogic: 'Natural wine bars are Paris\'s living rooms. No pretension, just good wine and the kind of conversations you can\'t plan.',
          },
        ],
      },
    ],
    changesSummary: null,
    createdAt: '2026-02-28T09:01:00Z',
  },

  // --- Version 1: Completionist proposal ---
  {
    id: V1_ID,
    sessionId: SESSION_ID,
    versionNumber: 1,
    agentId: 'completionist',
    commentary: 'Here\'s a **high-efficiency** Paris itinerary covering 12 key experiences in 48 hours. Every transition is walkable or one metro stop. I\'ve front-loaded mornings with timed-entry attractions to beat the crowds.',
    days: [
      {
        dayNumber: 1,
        theme: 'Iconic Paris Sprint',
        activities: [
          {
            id: '20000000-0000-4000-a000-000000000001',
            timeBlock: '08:00–10:00',
            title: 'Eiffel Tower (Timed Entry)',
            description: 'Pre-booked summit tickets for 8AM opening. Beat the crowds and get golden-hour photos from the top.',
            location: 'Champ de Mars, 75007',
            durationMinutes: 120,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'First slot of the day means virtually no wait. The morning light from the summit is unbeatable for photos. This is the #1 must-do and we knock it out first.',
          },
          {
            id: '20000000-0000-4000-a000-000000000002',
            timeBlock: '10:30–13:00',
            title: 'Musée d\'Orsay',
            description: 'Walk along the Seine to the museum. Focus on the Impressionist collection (Level 5). Pre-booked timed entry.',
            location: '1 Rue de la Légion d\'Honneur, 75007',
            durationMinutes: 150,
            category: 'culture',
            agentOrigin: 'completionist',
            agentLogic: 'A 20-minute walk from the Eiffel Tower along the Seine. The Impressionist galleries alone justify the visit. Timed entry eliminates the 45-minute queue.',
          },
          {
            id: '20000000-0000-4000-a000-000000000003',
            timeBlock: '13:00–14:00',
            title: 'Quick Lunch at Café Campana',
            description: 'Eat inside the Musée d\'Orsay\'s stunning Belle Époque restaurant. Skip the lines outside.',
            location: 'Inside Musée d\'Orsay',
            durationMinutes: 60,
            category: 'food',
            agentOrigin: 'completionist',
            agentLogic: 'Eating inside the museum saves 30+ minutes of restaurant hunting. The space itself is gorgeous — you\'re still sightseeing while eating.',
          },
          {
            id: '20000000-0000-4000-a000-000000000004',
            timeBlock: '14:30–16:30',
            title: 'Notre-Dame & Île de la Cité',
            description: 'See the reconstructed Notre-Dame exterior, walk through Île de la Cité, visit Sainte-Chapelle\'s stained glass.',
            location: 'Île de la Cité, 75004',
            durationMinutes: 120,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Notre-Dame\'s restoration is the story of 2026. Combined with Sainte-Chapelle (10 min walk), you get two iconic landmarks in one stop.',
          },
          {
            id: '20000000-0000-4000-a000-000000000005',
            timeBlock: '17:00–18:30',
            title: 'The Louvre (Exterior + Tuileries)',
            description: 'Pyramid photos, Tuileries Garden walk. Save the interior for a dedicated visit another time.',
            location: 'Jardin des Tuileries, 75001',
            durationMinutes: 90,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Trying to "do" the Louvre in 48h is a trap — you\'d spend 4 hours and see 1% of it. The exterior and gardens are free and photogenic.',
          },
          {
            id: '20000000-0000-4000-a000-000000000006',
            timeBlock: '19:30–21:30',
            title: 'Dinner Cruise on the Seine',
            description: 'Bateaux Mouches dinner cruise. See illuminated landmarks from the river — efficient sightseeing + dining combo.',
            location: 'Port de la Conférence, 75008',
            durationMinutes: 120,
            category: 'food',
            agentOrigin: 'completionist',
            agentLogic: 'Combines dinner + nighttime landmark viewing in one activity. You see the Eiffel Tower lit up, Notre-Dame, and the Conciergerie without walking a step.',
          },
        ],
      },
      {
        dayNumber: 2,
        theme: 'Culture & Heights',
        activities: [
          {
            id: '20000000-0000-4000-a000-000000000007',
            timeBlock: '08:30–10:30',
            title: 'Sacré-Cœur & Montmartre Quick Tour',
            description: 'Take the funicular up. Visit the basilica, enjoy the panoramic view, walk through Place du Tertre.',
            location: 'Sacré-Cœur, 75018',
            durationMinutes: 120,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Early morning means the artists in Place du Tertre are setting up and the basilica is nearly empty. The panoramic view rivals the Eiffel Tower.',
          },
          {
            id: '20000000-0000-4000-a000-000000000008',
            timeBlock: '11:00–13:00',
            title: 'Centre Pompidou',
            description: 'Modern art museum with rooftop views. Focus on Levels 4-5 (modern masterpieces) for maximum impact.',
            location: 'Place Georges-Pompidou, 75004',
            durationMinutes: 120,
            category: 'culture',
            agentOrigin: 'completionist',
            agentLogic: 'A 15-minute metro ride from Montmartre. The rooftop view alone is worth it, plus you cover modern art to complement the Impressionists from Day 1.',
          },
          {
            id: '20000000-0000-4000-a000-000000000009',
            timeBlock: '13:00–14:00',
            title: 'Falafel on Rue des Rosiers',
            description: 'L\'As du Fallafel in the Marais — consistently rated the best falafel in Paris. Expect a short queue.',
            location: 'Rue des Rosiers, 75004',
            durationMinutes: 60,
            category: 'food',
            agentOrigin: 'completionist',
            agentLogic: 'Three minutes from Pompidou. It\'s a Paris institution and the fastest quality meal in the Marais. Eat while walking to save time.',
          },
          {
            id: '20000000-0000-4000-a000-000000000010',
            timeBlock: '14:30–16:00',
            title: 'Père Lachaise Cemetery',
            description: 'Visit the graves of Jim Morrison, Oscar Wilde, Édith Piaf, and Chopin. Use the map app for efficient routing.',
            location: '16 Rue du Repos, 75020',
            durationMinutes: 90,
            category: 'culture',
            agentOrigin: 'completionist',
            agentLogic: 'Often skipped but absolutely worth it. The cemetery is a museum of sculpture and history. An efficient route hits the top 10 graves in 90 minutes.',
          },
          {
            id: '20000000-0000-4000-a000-000000000011',
            timeBlock: '16:30–18:00',
            title: 'Champs-Élysées & Arc de Triomphe',
            description: 'Walk the famous avenue, climb the Arc for sunset views over Paris. Pre-book Arc tickets.',
            location: 'Arc de Triomphe, 75008',
            durationMinutes: 90,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Timing for sunset from the Arc is perfect at this hour. The 360° view is arguably better than the Eiffel Tower and far less crowded.',
          },
          {
            id: '20000000-0000-4000-a000-000000000012',
            timeBlock: '19:00–21:00',
            title: 'Farewell Dinner at Le Bouillon Chartier',
            description: 'Historic Parisian brasserie with Belle Époque decor. Remarkable value — 3 courses under €25. No reservations.',
            location: '7 Rue du Faubourg Montmartre, 75009',
            durationMinutes: 120,
            category: 'food',
            agentOrigin: 'completionist',
            agentLogic: 'A Paris institution since 1896. The experience IS the destination — ornate dining room, fast service, classic dishes. Perfect capstone meal.',
          },
        ],
      },
    ],
    changesSummary: {
      dropped: [],
      added: [
        { title: 'Eiffel Tower (Timed Entry)', timeBlock: '08:00–10:00', agentOrigin: 'completionist' },
        { title: 'Musée d\'Orsay', timeBlock: '10:30–13:00', agentOrigin: 'completionist' },
        { title: 'Notre-Dame & Île de la Cité', timeBlock: '14:30–16:30', agentOrigin: 'completionist' },
        { title: 'Sacré-Cœur & Montmartre Quick Tour', timeBlock: '08:30–10:30', agentOrigin: 'completionist' },
        { title: 'Centre Pompidou', timeBlock: '11:00–13:00', agentOrigin: 'completionist' },
        { title: 'Arc de Triomphe', timeBlock: '16:30–18:00', agentOrigin: 'completionist' },
      ],
    },
    createdAt: '2026-02-28T09:02:00Z',
  },

  // --- Version 2: Master merge ---
  {
    id: V2_ID,
    sessionId: SESSION_ID,
    versionNumber: 2,
    agentId: 'master',
    commentary: 'I\'ve merged both proposals using the **Structured Drift** method: mornings for the Completionist\'s landmarks, afternoons for the Flâneur\'s wandering, and evenings negotiated by strongest option. The balance is 6 activities each.',
    days: [
      {
        dayNumber: 1,
        theme: 'Landmarks Meet Left Bank Drift',
        activities: [
          {
            id: '30000000-0000-4000-a000-000000000001',
            timeBlock: '08:00–10:00',
            title: 'Eiffel Tower (Timed Entry)',
            description: 'Pre-booked summit tickets for 8AM opening. Golden-hour photos from the top.',
            location: 'Champ de Mars, 75007',
            durationMinutes: 120,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'The Completionist\'s strongest morning pick. First slot means no crowds, and it sets an energetic tone for the day.',
          },
          {
            id: '30000000-0000-4000-a000-000000000002',
            timeBlock: '10:30–13:00',
            title: 'Musée d\'Orsay',
            description: 'Walk along the Seine. Focus on Level 5 Impressionists. Grab lunch at Café Campana inside.',
            location: '1 Rue de la Légion d\'Honneur, 75007',
            durationMinutes: 150,
            category: 'culture',
            agentOrigin: 'completionist',
            agentLogic: 'Logical next stop along the Seine. The in-museum lunch saves transition time while still feeling leisurely.',
          },
          {
            id: '30000000-0000-4000-a000-000000000003',
            timeBlock: '14:00–17:00',
            title: 'Luxembourg Gardens & Latin Quarter Drift',
            description: 'No agenda. Wander the gardens, sit by the fountain, browse bookshops. Follow your curiosity.',
            location: 'Jardin du Luxembourg, 75006',
            durationMinutes: 180,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'The Flâneur\'s afternoon philosophy shines here. After a structured morning, three hours of open exploration creates balance.',
          },
          {
            id: '30000000-0000-4000-a000-000000000004',
            timeBlock: '17:00–18:30',
            title: 'Rue Mouffetard Market Stroll',
            description: 'Late afternoon at one of Paris\'s oldest market streets. Sample cheese, chat with vendors.',
            location: 'Rue Mouffetard, 75005',
            durationMinutes: 90,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Condensed from the Flâneur\'s original morning slot. Late afternoon markets have a golden-hour glow and vendors are more chatty.',
          },
          {
            id: '30000000-0000-4000-a000-000000000005',
            timeBlock: '19:00–21:30',
            title: 'Dinner in Le Marais',
            description: 'Explore Le Marais for dinner — Chez Janou for chocolate mousse or the falafel row.',
            location: 'Le Marais, 75004',
            durationMinutes: 150,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'The Flâneur\'s evening pick wins here — Le Marais at dusk is more atmospheric than a Seine cruise, and you walk through a living neighborhood.',
          },
        ],
      },
      {
        dayNumber: 2,
        theme: 'Heights & Hidden Corners',
        activities: [
          {
            id: '30000000-0000-4000-a000-000000000006',
            timeBlock: '08:30–10:30',
            title: 'Sacré-Cœur & Montmartre Quick Tour',
            description: 'Funicular up, basilica visit, panoramic view, Place du Tertre.',
            location: 'Sacré-Cœur, 75018',
            durationMinutes: 120,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'The Completionist\'s efficient Montmartre coverage. Early arrival beats the crowds.',
          },
          {
            id: '30000000-0000-4000-a000-000000000007',
            timeBlock: '10:30–12:30',
            title: 'Montmartre Village Wander',
            description: 'Explore the cobblestone streets behind Sacré-Cœur. Artist studios, vineyard, quiet squares.',
            location: 'Montmartre, 75018',
            durationMinutes: 120,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'A concession to both agents — after the Completionist\'s quick tour, the Flâneur gets to show you the *real* Montmartre.',
          },
          {
            id: '30000000-0000-4000-a000-000000000008',
            timeBlock: '13:00–14:30',
            title: 'Canal Saint-Martin Picnic',
            description: 'Grab supplies from a fromagerie and settle along the canal. Watch the locks and boats.',
            location: 'Canal Saint-Martin, 75010',
            durationMinutes: 90,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'The Flâneur\'s picnic concept is both a meal and an activity. Cheaper and more Parisian than any restaurant.',
          },
          {
            id: '30000000-0000-4000-a000-000000000009',
            timeBlock: '15:00–17:00',
            title: 'Canal Walks & Vintage Shopping',
            description: 'Follow the canal, browse vintage shops on Rue Beaurepaire.',
            location: 'Canal Saint-Martin area, 75010',
            durationMinutes: 120,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Afternoon drift along the canal. The 10th arrondissement rewards those who wander.',
          },
          {
            id: '30000000-0000-4000-a000-000000000010',
            timeBlock: '17:30–18:30',
            title: 'Arc de Triomphe at Sunset',
            description: 'Climb the Arc for sunset panoramic views. Pre-booked tickets.',
            location: 'Arc de Triomphe, 75008',
            durationMinutes: 60,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'The Completionist\'s sunset timing is perfect. A quick metro ride from the 10th, and the 360° view caps the trip.',
          },
          {
            id: '30000000-0000-4000-a000-000000000011',
            timeBlock: '20:00–22:00',
            title: 'Natural Wine Bar Evening',
            description: 'End at Le Verre Volé — small plates, interesting wines, conversation.',
            location: '67 Rue de Lancry, 75010',
            durationMinutes: 120,
            category: 'nightlife',
            agentOrigin: 'flaneur',
            agentLogic: 'The Flâneur\'s wine bar closing is more intimate than the Completionist\'s brasserie, and it caps a day that started in the same neighborhood.',
          },
        ],
      },
    ],
    changesSummary: {
      dropped: [
        { title: 'Café de Flore Morning', timeBlock: '09:00–10:30' },
        { title: 'Notre-Dame & Île de la Cité', timeBlock: '14:30–16:30' },
        { title: 'The Louvre (Exterior + Tuileries)', timeBlock: '17:00–18:30' },
        { title: 'Dinner Cruise on the Seine', timeBlock: '19:30–21:30' },
        { title: 'Centre Pompidou', timeBlock: '11:00–13:00' },
        { title: 'Père Lachaise Cemetery', timeBlock: '14:30–16:00' },
        { title: 'Farewell Dinner at Le Bouillon Chartier', timeBlock: '19:00–21:00' },
      ],
      added: [
        { title: 'Eiffel Tower (Timed Entry)', timeBlock: '08:00–10:00', agentOrigin: 'completionist' },
        { title: 'Musée d\'Orsay', timeBlock: '10:30–13:00', agentOrigin: 'completionist' },
        { title: 'Luxembourg Gardens & Latin Quarter Drift', timeBlock: '14:00–17:00', agentOrigin: 'flaneur' },
        { title: 'Sacré-Cœur & Montmartre Quick Tour', timeBlock: '08:30–10:30', agentOrigin: 'completionist' },
        { title: 'Arc de Triomphe at Sunset', timeBlock: '17:30–18:30', agentOrigin: 'completionist' },
      ],
    },
    createdAt: '2026-02-28T09:03:00Z',
  },

  // --- Version 3: Flaneur critique ---
  {
    id: V3_ID,
    sessionId: SESSION_ID,
    versionNumber: 3,
    agentId: 'flaneur',
    commentary: 'The merge is solid, but Day 1 morning still feels rushed. I\'ve swapped the Eiffel Tower for a slower start — you can see the tower from the Seine walk without queuing. Also restored Café de Flore because some mornings deserve to be slow.',
    days: [
      {
        dayNumber: 1,
        theme: 'A Gentler Start',
        activities: [
          {
            id: '40000000-0000-4000-a000-000000000001',
            timeBlock: '09:00–10:30',
            title: 'Café de Flore Morning',
            description: 'Start slow at this Saint-Germain institution. Café crème, terrace seat, watch the neighborhood.',
            location: '172 Boulevard Saint-Germain, 75006',
            durationMinutes: 90,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'Restored from my original proposal. An 8AM Eiffel Tower sprint is antithetical to experiencing Paris. You deserve a real morning.',
          },
          {
            id: '40000000-0000-4000-a000-000000000002',
            timeBlock: '10:30–13:00',
            title: 'Musée d\'Orsay',
            description: 'Walk along the Seine. Level 5 Impressionists. Lunch at Café Campana.',
            location: '1 Rue de la Légion d\'Honneur, 75007',
            durationMinutes: 150,
            category: 'culture',
            agentOrigin: 'completionist',
            agentLogic: 'Kept from the merge — this is genuinely worth the structured time. The walk from Saint-Germain is even more natural than from the Eiffel Tower.',
          },
          {
            id: '40000000-0000-4000-a000-000000000003',
            timeBlock: '14:00–17:00',
            title: 'Luxembourg Gardens & Latin Quarter Drift',
            description: 'No agenda. Gardens, bookshops, hidden courtyards.',
            location: 'Jardin du Luxembourg, 75006',
            durationMinutes: 180,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged from the merge. This is the heart of the slow-travel philosophy.',
          },
          {
            id: '40000000-0000-4000-a000-000000000004',
            timeBlock: '17:00–18:30',
            title: 'Rue Mouffetard Market Stroll',
            description: 'Late afternoon market browsing and snacking.',
            location: 'Rue Mouffetard, 75005',
            durationMinutes: 90,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged. The market into evening dinner flow is natural.',
          },
          {
            id: '40000000-0000-4000-a000-000000000005',
            timeBlock: '19:00–21:30',
            title: 'Dinner in Le Marais',
            description: 'Chez Janou, falafel row, or wherever the energy takes you.',
            location: 'Le Marais, 75004',
            durationMinutes: 150,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged. Evening Le Marais is non-negotiable.',
          },
        ],
      },
      {
        dayNumber: 2,
        theme: 'Heights & Hidden Corners',
        activities: [
          {
            id: '40000000-0000-4000-a000-000000000006',
            timeBlock: '08:30–10:30',
            title: 'Sacré-Cœur & Montmartre Quick Tour',
            description: 'Funicular up, basilica, panoramic view, Place du Tertre.',
            location: 'Sacré-Cœur, 75018',
            durationMinutes: 120,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Kept — the early morning Sacré-Cœur visit is worth the structure.',
          },
          {
            id: '40000000-0000-4000-a000-000000000007',
            timeBlock: '10:30–12:30',
            title: 'Montmartre Village Wander',
            description: 'Cobblestone streets, artist studios, vineyard, quiet squares.',
            location: 'Montmartre, 75018',
            durationMinutes: 120,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged. The real Montmartre is behind Sacré-Cœur.',
          },
          {
            id: '40000000-0000-4000-a000-000000000008',
            timeBlock: '13:00–14:30',
            title: 'Canal Saint-Martin Picnic',
            description: 'Fromagerie supplies, canal-side lunch.',
            location: 'Canal Saint-Martin, 75010',
            durationMinutes: 90,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged. Peak Parisian living.',
          },
          {
            id: '40000000-0000-4000-a000-000000000009',
            timeBlock: '15:00–17:00',
            title: 'Canal Walks & Vintage Shopping',
            description: 'Follow the canal, browse vintage shops.',
            location: 'Canal Saint-Martin area, 75010',
            durationMinutes: 120,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged. Afternoon canal drift.',
          },
          {
            id: '40000000-0000-4000-a000-000000000010',
            timeBlock: '17:30–18:30',
            title: 'Arc de Triomphe at Sunset',
            description: 'Sunset panoramic views from the Arc.',
            location: 'Arc de Triomphe, 75008',
            durationMinutes: 60,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Kept — the sunset timing is genuinely good.',
          },
          {
            id: '40000000-0000-4000-a000-000000000011',
            timeBlock: '20:00–22:00',
            title: 'Natural Wine Bar Evening',
            description: 'Le Verre Volé — small plates, natural wines, locals.',
            location: '67 Rue de Lancry, 75010',
            durationMinutes: 120,
            category: 'nightlife',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged. The perfect ending.',
          },
        ],
      },
    ],
    changesSummary: {
      dropped: [
        { title: 'Eiffel Tower (Timed Entry)', timeBlock: '08:00–10:00' },
      ],
      added: [
        { title: 'Café de Flore Morning', timeBlock: '09:00–10:30', agentOrigin: 'flaneur' },
      ],
    },
    createdAt: '2026-02-28T09:04:00Z',
  },

  // --- Version 4: Completionist critique ---
  {
    id: V4_ID,
    sessionId: SESSION_ID,
    versionNumber: 4,
    agentId: 'completionist',
    commentary: 'Removing the Eiffel Tower from a 48-hour Paris trip is criminal. I\'ve restored it as a late-afternoon activity on Day 1 — **sunset from the tower** is even better than morning. Also added Notre-Dame as a quick stop since it\'s on the Day 1 route.',
    days: [
      {
        dayNumber: 1,
        theme: 'Culture & Icons',
        activities: [
          {
            id: '50000000-0000-4000-a000-000000000001',
            timeBlock: '09:00–10:30',
            title: 'Café de Flore Morning',
            description: 'Café crème at this Saint-Germain institution.',
            location: '172 Boulevard Saint-Germain, 75006',
            durationMinutes: 90,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'Accepted — a slower morning start is a reasonable compromise.',
          },
          {
            id: '50000000-0000-4000-a000-000000000002',
            timeBlock: '10:30–13:00',
            title: 'Musée d\'Orsay',
            description: 'Walk along the Seine. Level 5 Impressionists. Lunch at Café Campana.',
            location: '1 Rue de la Légion d\'Honneur, 75007',
            durationMinutes: 150,
            category: 'culture',
            agentOrigin: 'completionist',
            agentLogic: 'Unchanged. Essential cultural stop.',
          },
          {
            id: '50000000-0000-4000-a000-000000000003',
            timeBlock: '13:30–14:30',
            title: 'Notre-Dame & Île de la Cité',
            description: 'Quick visit to see the restored Notre-Dame exterior. Walk across to Île Saint-Louis for a Berthillon ice cream.',
            location: 'Île de la Cité, 75004',
            durationMinutes: 60,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Added back — it\'s directly on the walking route from Orsay to the Latin Quarter. A 30-minute exterior visit + ice cream won\'t break the flow.',
          },
          {
            id: '50000000-0000-4000-a000-000000000004',
            timeBlock: '14:30–17:00',
            title: 'Luxembourg Gardens & Latin Quarter Drift',
            description: 'No agenda. Gardens, bookshops, hidden courtyards.',
            location: 'Jardin du Luxembourg, 75006',
            durationMinutes: 150,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Kept but trimmed 30 minutes to accommodate Notre-Dame. Still a generous drift window.',
          },
          {
            id: '50000000-0000-4000-a000-000000000005',
            timeBlock: '17:30–19:30',
            title: 'Eiffel Tower at Sunset',
            description: 'Pre-booked sunset tickets. Watch the city light up from the summit, then see the tower sparkle on the hour.',
            location: 'Champ de Mars, 75007',
            durationMinutes: 120,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Restored and improved — sunset from the Eiffel Tower is even better than morning. The hourly sparkle at nightfall is an unforgettable moment.',
          },
          {
            id: '50000000-0000-4000-a000-000000000006',
            timeBlock: '20:00–22:00',
            title: 'Dinner in Le Marais',
            description: 'Chez Janou, falafel row, or wherever the energy takes you.',
            location: 'Le Marais, 75004',
            durationMinutes: 120,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'Kept — pushed back slightly to accommodate sunset tower. The Marais is great after 8PM.',
          },
        ],
      },
      {
        dayNumber: 2,
        theme: 'Heights & Hidden Corners',
        activities: [
          {
            id: '50000000-0000-4000-a000-000000000007',
            timeBlock: '08:30–10:30',
            title: 'Sacré-Cœur & Montmartre Quick Tour',
            description: 'Funicular up, basilica, panoramic view, Place du Tertre.',
            location: 'Sacré-Cœur, 75018',
            durationMinutes: 120,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Unchanged. Early Sacré-Cœur is unbeatable.',
          },
          {
            id: '50000000-0000-4000-a000-000000000008',
            timeBlock: '10:30–12:30',
            title: 'Montmartre Village Wander',
            description: 'Cobblestone streets, artist studios, vineyard, quiet squares.',
            location: 'Montmartre, 75018',
            durationMinutes: 120,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged. Good complement to the structured morning.',
          },
          {
            id: '50000000-0000-4000-a000-000000000009',
            timeBlock: '13:00–14:30',
            title: 'Canal Saint-Martin Picnic',
            description: 'Fromagerie supplies, canal-side lunch.',
            location: 'Canal Saint-Martin, 75010',
            durationMinutes: 90,
            category: 'food',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged.',
          },
          {
            id: '50000000-0000-4000-a000-000000000010',
            timeBlock: '15:00–17:00',
            title: 'Canal Walks & Vintage Shopping',
            description: 'Follow the canal, browse vintage shops.',
            location: 'Canal Saint-Martin area, 75010',
            durationMinutes: 120,
            category: 'free-roam',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged.',
          },
          {
            id: '50000000-0000-4000-a000-000000000011',
            timeBlock: '17:30–18:30',
            title: 'Arc de Triomphe at Sunset',
            description: 'Sunset panoramic views from the Arc.',
            location: 'Arc de Triomphe, 75008',
            durationMinutes: 60,
            category: 'landmark',
            agentOrigin: 'completionist',
            agentLogic: 'Unchanged.',
          },
          {
            id: '50000000-0000-4000-a000-000000000012',
            timeBlock: '20:00–22:00',
            title: 'Natural Wine Bar Evening',
            description: 'Le Verre Volé — small plates, natural wines, locals.',
            location: '67 Rue de Lancry, 75010',
            durationMinutes: 120,
            category: 'nightlife',
            agentOrigin: 'flaneur',
            agentLogic: 'Unchanged. Good ending.',
          },
        ],
      },
    ],
    changesSummary: {
      dropped: [
        { title: 'Rue Mouffetard Market Stroll', timeBlock: '17:00–18:30' },
      ],
      added: [
        { title: 'Notre-Dame & Île de la Cité', timeBlock: '13:30–14:30', agentOrigin: 'completionist' },
        { title: 'Eiffel Tower at Sunset', timeBlock: '17:30–19:30', agentOrigin: 'completionist' },
      ],
    },
    createdAt: '2026-02-28T09:05:00Z',
  },
]

export const mockMessages: ChatMessage[] = [
  {
    id: '90000000-0000-4000-a000-000000000001',
    sessionId: SESSION_ID,
    agentId: 'flaneur',
    role: 'proposal',
    content: mockVersions[0].commentary,
    relatedVersionId: V0_ID,
    createdAt: '2026-02-28T09:01:00Z',
  },
  {
    id: '90000000-0000-4000-a000-000000000002',
    sessionId: SESSION_ID,
    agentId: 'completionist',
    role: 'proposal',
    content: mockVersions[1].commentary,
    relatedVersionId: V1_ID,
    createdAt: '2026-02-28T09:02:00Z',
  },
  {
    id: '90000000-0000-4000-a000-000000000003',
    sessionId: SESSION_ID,
    agentId: 'user',
    role: 'user-input',
    content: 'I really want to see the Eiffel Tower — don\'t skip it! But I also love the idea of a canal picnic.',
    createdAt: '2026-02-28T09:02:30Z',
  },
  {
    id: '90000000-0000-4000-a000-000000000004',
    sessionId: SESSION_ID,
    agentId: 'master',
    role: 'merge',
    content: mockVersions[2].commentary,
    relatedVersionId: V2_ID,
    createdAt: '2026-02-28T09:03:00Z',
  },
  {
    id: '90000000-0000-4000-a000-000000000005',
    sessionId: SESSION_ID,
    agentId: 'flaneur',
    role: 'critique',
    content: mockVersions[3].commentary,
    relatedVersionId: V3_ID,
    createdAt: '2026-02-28T09:04:00Z',
  },
  {
    id: '90000000-0000-4000-a000-000000000006',
    sessionId: SESSION_ID,
    agentId: 'user',
    role: 'user-input',
    content: 'The Eiffel Tower at sunset sounds amazing — definitely keep that!',
    createdAt: '2026-02-28T09:04:30Z',
  },
  {
    id: '90000000-0000-4000-a000-000000000007',
    sessionId: SESSION_ID,
    agentId: 'completionist',
    role: 'critique',
    content: mockVersions[4].commentary,
    relatedVersionId: V4_ID,
    createdAt: '2026-02-28T09:05:00Z',
  },
]
